
https://api.themoviedb.org/3/movie/76341?api_key=394ba4836fb2f67bf883e42b3463c4d9

###

https://api.themoviedb.org/3/search/movie?api_key=394ba4836fb2f67bf883e42b3463c4d9&language=en-US&page=1&query=avengers

###

https://api.themoviedb.org/3/genre/movie/list?api_key=394ba4836fb2f67bf883e42b3463c4d9

###

https://api.themoviedb.org/3/discover/movie?api_key=394ba4836fb2f67bf883e42b3463c4d9&language=en-US&with_genres=28

###

https://api.themoviedb.org/3/movie/76341/credits?api_key=394ba4836fb2f67bf883e42b3463c4d9

###

https://api.themoviedb.org/3/person/2524?api_key=394ba4836fb2f67bf883e42b3463c4d9&language=en-US